contracts/.babelrc, contracts/README.md, contracts/contracts/Linkdrop.sol, contracts/contracts/LinkdropERC721.sol, contracts/contracts/interfaces/ILinkdrop.sol, contracts/contracts/interfaces/ILinkdropERC721.sol, contracts/contracts/mocks/NFTMock.sol, contracts/contracts/mocks/TokenMock.sol, contracts/package.json, contracts/test/Linkdrop.js, contracts/test/LinkdropERC721.js
Linkdrop contract now supports ERC20 and ethers. Covered with tests using Waffle
=> Added Linkdrop contract and tests

.babelrc, contracts/.babelrc, contracts/contracts/Factory.sol, contracts/contracts/Linkdrop.sol, contracts/contracts/LinkdropERC721.sol, contracts/contracts/interfaces/ILinkdrop.sol, contracts/contracts/interfaces/ILinkdropERC721.sol, contracts/scripts/deploy.js, contracts/scripts/utils.js, contracts/test/Claim.js, yarn.lock
Now factory has claim function which checks whether a proxy contract is deployed for sender and deploys in case not and after claims required tokens
=> Implemented claim function

README.md
new readme file for new structure of monorepo
=> added new readme file

app-claim/components/pages/main/claiming-process-page/index.js, app-claim/components/pages/main/index.js, app-claim/components/pages/main/wallet-choose-page/index.js
=> added translations for comments

server/package.json, server/server.js
@Dobrokhvalov Implemented issue #83
=> Added cors support

contracts/contracts/Common.sol, contracts/contracts/Factory.sol, contracts/contracts/Linkdrop.sol, contracts/contracts/LinkdropERC721.sol, contracts/contracts/Mastercopy.sol, contracts/contracts/Storage.sol, contracts/contracts/mocks/NFTMock.sol, contracts/contracts/mocks/TokenMock.sol, contracts/test/Linkdrop.js, contracts/test/LinkdropERC721.js
@Dobrokhvalov Implemented issue #76
=> Added comments and new tests to contracts

sdk/README.md, sdk/src/claim.js
@Dobrokhvalov Implemented issue #75
=> Added readme for linkdrop-sdk

contracts/contracts/Factory.sol, contracts/contracts/Linkdrop.sol, contracts/contracts/LinkdropERC721.sol, contracts/test/Linkdrop.js, contracts/test/LinkdropERC721.js
@Dobrokhvalov Implemented issue #87
=> Added support for approve pattern

app-claim/data/store/saga/tokens/every/claim-tokens-erc20.js, app-claim/data/store/saga/tokens/every/claim-tokens-erc721.js, app-landing/data/store/saga/user/every/generate-link-erc20.js, app-landing/data/store/saga/user/every/generate-link-erc721.js
=> changes for host split

scripts/src/claim_erc20.js, scripts/src/claim_erc721.js, scripts/src/claim_eth.js, scripts/src/index.js, sdk/src/claim.js, sdk/src/computeProxyAddress.js, sdk/src/generateLink.js
=> Added params validation to SDK

contracts/contracts/Factory.sol, contracts/contracts/LinkdropERC721.sol, contracts/test/Linkdrop.js, contracts/test/LinkdropERC721.js
=> Changed factory contract

sdk/src/claim.js
=> Added minor fix to sdk

app-claim/data/store/saga/contract/every/get-token-erc721-data.js
change for nft token call fallback
=> added update for api call

app-landing/components/common/header/styles.module.scss
=> added fixes for landing

app-landing/components/common/header/styles.module.scss
added fixes for landing bounty header align items
=> added fixes for landing bounty header

app-claim/components/application/router/styles.css, app-landing/components/application/router/styles.css
=> added fixes for zoom bug

app-claim/components/pages/main/wallet-choose-page/index.js, app-claim/components/pages/main/wallet-choose-page/slider/index.js, app-claim/components/pages/main/wallet-choose-page/styles.module.scss, app-claim/components/pages/page/styles.module.scss, config/wallets.js
=> added fixes for wallet choose

app-claim/components/pages/main/wallet-choose-page/slider/index.js
=> added fixes for wallets list

linkdrop-ui-kit/.babelrc
removed babelrc from linkdrop ui kit
=> removed babelrc

app-landing/components/common/header/styles.module.scss, app-landing/components/pages/main/index.js, app-landing/components/pages/main/tokens-send/index.js, app-landing/components/pages/main/tokens-send/styles.module.scss, app-landing/texts/en/components/header/index.js, app-landing/texts/en/pages/main/index.js
added some minor fixes for texts, template and added link to connect with telegram with support
=> added fixes to texts

app-claim/components/application/index.js, app-landing/components/application/connectors/index.js, app-landing/components/application/index.js, app-landing/components/application/router-provider/index.js, app-landing/components/pages/main/index.js, app-landing/package.json, yarn.lock
web3-react added to app-landing with infura and metamask connectors
=> added web3-react

config/scripts.config.json.sample, scripts/src/claim_erc20.js, scripts/src/claim_erc721.js, scripts/src/claim_eth.js, scripts/src/generate_links_erc20.js, scripts/src/generate_links_erc721.js, scripts/src/generate_links_eth.js, scripts/src/index.js, sdk/src/claim.js, sdk/src/generateLink.js, server/controllers/claimController.js, server/models/claimTx.js, server/models/claimTxERC721.js
=> Updated SDK, scripts and server to support `approve` pattern

app-claim/components/pages/main/claiming-process-page/index.js, app-claim/components/pages/main/index.js, app-claim/data/actions/tokens.js, app-claim/data/store/saga/tokens/every/check-if-claimed.js, app-claim/data/store/saga/tokens/every/claim-tokens-erc20.js, app-claim/data/store/saga/tokens/every/claim-tokens-erc721.js, app-claim/test/saga/tokens/every/claim-tokens-erc20.js, app-claim/test/saga/tokens/every/claim-tokens-erc721.js, app-landing/data/store/saga/user/every/generate-link-erc20.js, app-landing/data/store/saga/user/every/generate-link-erc721.js, app-landing/test/user/every/generate-link-erc20.js, app-landing/test/user/every/generate-link-erc721.js
fix for approve logic + sdk format change
=> Dev fix for approve

contracts/contracts/factory/LinkdropFactory.sol, contracts/contracts/factory/LinkdropFactoryCommon.sol, contracts/contracts/factory/LinkdropFactoryERC20.sol, contracts/contracts/factory/LinkdropFactoryERC721.sol, contracts/contracts/factory/approve/LinkdropFactoryERC20Approve.sol, contracts/contracts/factory/approve/LinkdropFactoryERC721Approve.sol, contracts/contracts/interfaces/ILinkdropCommon.sol, contracts/contracts/interfaces/ILinkdropERC20.sol, contracts/contracts/interfaces/ILinkdropERC721.sol, contracts/contracts/interfaces/ILinkdropFactoryERC20.sol, contracts/contracts/interfaces/ILinkdropFactoryERC721.sol, contracts/contracts/interfaces/approve/ILinkdropERC20Approve.sol, contracts/contracts/interfaces/approve/ILinkdropERC721Approve.sol, contracts/contracts/interfaces/approve/ILinkdropFactoryERC20Approve.sol, contracts/contracts/interfaces/approve/ILinkdropFactoryERC721Approve.sol, contracts/contracts/linkdrop/LinkdropCommon.sol, contracts/contracts/linkdrop/LinkdropERC20.sol, contracts/contracts/linkdrop/LinkdropERC721.sol, contracts/contracts/linkdrop/approve/LinkdropERC20Approve.sol, contracts/contracts/linkdrop/approve/LinkdropERC721Approve.sol, contracts/contracts/storage/LinkdropFactoryStorage.sol, contracts/contracts/storage/LinkdropStorage.sol, contracts/scripts/utils.js, contracts/test/LinkdropERC20.js, contracts/test/LinkdropERC20Approve.js, contracts/test/LinkdropERC721.js, contracts/test/LinkdropERC721Approve.js, contracts/test/Upgradable.js
=> Added chain id check

app-landing/components/pages/main/metamask-injected-screen/index.js, app-landing/components/pages/main/metamask-injected-screen/styles.module.scss, app-landing/data/store/saga/metamask/every/check-asset-presence.js, app-landing/data/store/saga/metamask/every/get-asset-balance.js, app-landing/data/store/saga/metamask/every/send-tokens-from-metamask.js, app-landing/data/store/saga/tokens/every/check-erc721-balance.js, app-landing/package.json, app-landing/texts/en/pages/main/index.js, yarn.lock
added some validations, debounce, alerts
=> added alerts

apps/app-landing/data/store/saga/user/every/generate-link-erc721.js
=> added fix for front end part for erc721

scripts/src/claim_erc20.js, scripts/src/claim_erc721.js, scripts/src/claim_eth.js, scripts/src/utils.js, server/controllers/claimController.js
=> Added fix for the backend

contracts/contracts/factory/LinkdropFactoryCommon.sol, contracts/contracts/linkdrop/LinkdropCommon.sol, contracts/test/DeployWithSigner.js, yarn.lock
=> Added deploy proxy with signer method

scripts/src/generate_links_erc20.js, scripts/src/generate_links_erc721.js, scripts/src/generate_links_eth.js, sdk/src/generateLink.js
=> Updated SDK

server/deploy/shipitfile.js, server/package.json
=> Added ropsten support

apps/app-dashboard/components/pages/campaigns/index.js, apps/app-dashboard/components/pages/main/index.js, apps/app-dashboard/texts/en/pages/main/index.js
update for texts and filtering
=> added fixes for filtering and texts

contracts/contracts/factory/LinkdropFactoryERC20.sol, contracts/contracts/factory/LinkdropFactoryERC721.sol, contracts/contracts/linkdrop/LinkdropERC20.sol, contracts/contracts/linkdrop/LinkdropERC721.sol, contracts/contracts/mocks/NFTMock.sol, contracts/test/LinkdropERC20.js, contracts/test/LinkdropERC721.js
=> Added additional balance checks to contracts

scripts/src/claim_erc20.js, scripts/src/claim_erc721.js, scripts/src/claim_eth.js, scripts/src/utils.js
=> Link number arguement added to scripts 

contracts/contracts/factory/LinkdropFactoryERC20.sol, contracts/contracts/factory/LinkdropFactoryERC721.sol, contracts/contracts/interfaces/ILinkdropFactoryERC20.sol, contracts/contracts/interfaces/ILinkdropFactoryERC721.sol, contracts/test/LinkdropERC20.js, contracts/test/LinkdropERC721.js
=> Removed checkClaimParams from Factory

packages/apps/app-claim/data/sdk/index.js, packages/apps/app-claim/data/store/saga/user/every/create-sdk.js, packages/apps/app-dashboard/data/sdk/index.js
Reverts LinkdropHQ/linkdrop-monorepo#391
=> Revert "Staging"

packages/apps/app-claim/app.config.js, packages/apps/app-claim/data/store/saga/user/every/create-sdk.js, packages/apps/app-claim/webpack.common.js, packages/apps/app-dashboard/app.config.js, packages/apps/app-dashboard/data/store/saga/user/every/check-current-provider.js, packages/apps/app-dashboard/webpack.common.js
Reverts LinkdropHQ/linkdrop-monorepo#408
=> Revert infura-pk changes as they don't work
